name: r_env
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _r-mutex=1.0.1
  - anyio=4.8.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=25.1.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cairo=1.18.2
  - cctools_osx-64=1010.6
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - clang=19.1.7
  - clang-19=19.1.7
  - clang_impl_osx-64=19.1.7
  - clang_osx-64=19.1.7
  - clangxx=19.1.7
  - clangxx_impl_osx-64=19.1.7
  - clangxx_osx-64=19.1.7
  - comm=0.2.2
  - compiler-rt=19.1.7
  - compiler-rt_osx-64=19.1.7
  - curl=8.12.1
  - debugpy=1.8.12
  - decorator=5.2.0
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gfortran_impl_osx-64=13.2.0
  - gfortran_osx-64=13.2.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7.1
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=9.0.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.32.0
  - isl=0.26
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - krb5=1.21.3
  - ld64_osx-64=951.9
  - lerc=4.0.0
  - libasprintf=0.23.1
  - libblas=3.9.0
  - libcurl=8.12.1
  - libcxx=19.1.7
  - libcxx-devel=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=4.8.5
  - libgettextpo=0.23.1
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libiconv=1.18
  - libintl=0.23.1
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxml2=2.13.6
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - llvm-tools=19.1.7
  - llvm-tools-19=19.1.7
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - openssl=3.4.1
  - overrides=7.7.0
  - packaging=24.2
  - pandoc=3.6.3
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pysocks=1.7.1
  - python=3.11
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=3.2.1
  - python_abi=3.13
  - pytz=2025.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.4.2
  - r-base64enc=0.1_3
  - r-bit=4.5.0.1
  - r-bit64=4.5.2
  - r-blob=1.2.4
  - r-boot=1.3_31
  - r-broom=1.0.7
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-class=7.3_23
  - r-cli=3.6.4
  - r-clipr=0.8.0
  - r-clock=0.7.1
  - r-cluster=2.1.8
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-commonmark=1.9.2
  - r-conflicted=1.2.0
  - r-cpp11=0.5.1
  - r-crayon=1.5.3
  - r-crul=1.5.0
  - r-curl=6.0.1
  - r-data.table=1.17.0
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-diagram=1.6.5
  - r-digest=0.6.37
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-essentials=4.4
  - r-evaluate=1.0.
